// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6119437942335147334),
    name: 'MessageEntity',
    lastPropertyId: const obx_int.IdUid(8, 2668854574544022426),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 350168203629889537),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4195520045590035982),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 232624627906074633),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7734140013487755088),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4625843809280208235),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4653844258108182703),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9082883577868892284),
        name: 'tasksJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4589590074721314060),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 1514269524083475147),
        hnswParams: obx_int.ModelHnswParams(
          dimensions: 1536,
          neighborsPerNode: 30,
          indexingSearchCount: 200,
        ),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2668854574544022426),
        name: 'projectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 2761407742651527344),
        relationField: 'project',
        relationTarget: 'ProjectEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5787452846158435810),
    name: 'ProjectEntity',
    lastPropertyId: const obx_int.IdUid(6, 7891003221259516193),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 660245880672328721),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 82201311848862795),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 1991264806254853480),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8881745603239392488),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6509396384659871972),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2091521768350385486),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7891003221259516193),
        name: 'colorHex',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'messages',
        srcEntity: 'MessageEntity',
        srcField: 'project',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5489887417224204944),
    name: 'CalendarTaskEntity',
    lastPropertyId: const obx_int.IdUid(17, 6025903371449862582),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4518308446815436143),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7666829019756962203),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 8981654602520316427),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6692342963394657335),
        name: 'taskName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5071313082721512622),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3869015664579259702),
        name: 'dueDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4427087298963051728),
        name: 'calendarDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1082396706250896546),
        name: 'priority',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7394848531446461073),
        name: 'timeToComplete',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3470654104147902098),
        name: 'links',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 655511590630379070),
        name: 'projectId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6319842858851574866),
        name: 'messageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2311140181716785448),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 9198470597964884342),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 9184180476329030146),
        name: 'originalTaskId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2967780426182221388),
        name: 'startTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3445624337483829038),
        name: 'endTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6025903371449862582),
        name: 'isManuallyScheduled',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 5489887417224204944),
    lastIndexId: const obx_int.IdUid(5, 8981654602520316427),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MessageEntity: obx_int.EntityDefinition<MessageEntity>(
      model: _entities[0],
      toOneRelations: (MessageEntity object) => [object.project],
      toManyRelations: (MessageEntity object) => {},
      getId: (MessageEntity object) => object.id,
      setId: (MessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MessageEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final roleOffset = fbb.writeString(object.role);
        final textOffset = fbb.writeString(object.text);
        final tasksJsonOffset = object.tasksJson == null
            ? null
            : fbb.writeString(object.tasksJson!);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, roleOffset);
        fbb.addOffset(3, textOffset);
        fbb.addInt64(4, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(5, tasksJsonOffset);
        fbb.addOffset(6, embeddingOffset);
        fbb.addInt64(7, object.project.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final tasksJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = MessageEntity(
          id: idParam,
          uuid: uuidParam,
          role: roleParam,
          text: textParam,
          timestamp: timestampParam,
          tasksJson: tasksJsonParam,
          embedding: embeddingParam,
        );
        object.project.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.project.attach(store);
        return object;
      },
    ),
    ProjectEntity: obx_int.EntityDefinition<ProjectEntity>(
      model: _entities[1],
      toOneRelations: (ProjectEntity object) => [],
      toManyRelations: (ProjectEntity object) => {
        obx_int.RelInfo<MessageEntity>.toOneBacklink(
          8,
          object.id,
          (MessageEntity srcObject) => srcObject.project,
        ): object.messages,
      },
      getId: (ProjectEntity object) => object.id,
      setId: (ProjectEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProjectEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final colorHexOffset = object.colorHex == null
            ? null
            : fbb.writeString(object.colorHex!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, createdAtOffset);
        fbb.addOffset(5, colorHexOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final colorHexParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = ProjectEntity(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          description: descriptionParam,
          createdAt: createdAtParam,
          colorHex: colorHexParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<ProjectEntity>(
          object.messages,
          store,
          obx_int.RelInfo<MessageEntity>.toOneBacklink(
            8,
            object.id,
            (MessageEntity srcObject) => srcObject.project,
          ),
        );
        return object;
      },
    ),
    CalendarTaskEntity: obx_int.EntityDefinition<CalendarTaskEntity>(
      model: _entities[2],
      toOneRelations: (CalendarTaskEntity object) => [],
      toManyRelations: (CalendarTaskEntity object) => {},
      getId: (CalendarTaskEntity object) => object.id,
      setId: (CalendarTaskEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CalendarTaskEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final taskNameOffset = fbb.writeString(object.taskName);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final linksOffset = object.links == null
            ? null
            : fbb.writeString(object.links!);
        final projectIdOffset = object.projectId == null
            ? null
            : fbb.writeString(object.projectId!);
        final messageIdOffset = object.messageId == null
            ? null
            : fbb.writeString(object.messageId!);
        final originalTaskIdOffset = object.originalTaskId == null
            ? null
            : fbb.writeString(object.originalTaskId!);
        final startTimeOffset = object.startTime == null
            ? null
            : fbb.writeString(object.startTime!);
        final endTimeOffset = object.endTime == null
            ? null
            : fbb.writeString(object.endTime!);
        fbb.startTable(18);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, taskNameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.dueDate?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.calendarDate.millisecondsSinceEpoch);
        fbb.addInt64(6, object.priority);
        fbb.addInt64(7, object.timeToComplete);
        fbb.addOffset(8, linksOffset);
        fbb.addOffset(9, projectIdOffset);
        fbb.addOffset(10, messageIdOffset);
        fbb.addBool(11, object.isCompleted);
        fbb.addInt64(12, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(13, originalTaskIdOffset);
        fbb.addOffset(14, startTimeOffset);
        fbb.addOffset(15, endTimeOffset);
        fbb.addBool(16, object.isManuallyScheduled);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dueDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final originalTaskIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final taskNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final dueDateParam = dueDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dueDateValue);
        final calendarDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final startTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final endTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final priorityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final timeToCompleteParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final linksParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final projectIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final messageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final isManuallyScheduledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          36,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
        );
        final object = CalendarTaskEntity(
          id: idParam,
          uuid: uuidParam,
          originalTaskId: originalTaskIdParam,
          taskName: taskNameParam,
          description: descriptionParam,
          dueDate: dueDateParam,
          calendarDate: calendarDateParam,
          startTime: startTimeParam,
          endTime: endTimeParam,
          priority: priorityParam,
          timeToComplete: timeToCompleteParam,
          links: linksParam,
          projectId: projectIdParam,
          messageId: messageIdParam,
          isCompleted: isCompletedParam,
          isManuallyScheduled: isManuallyScheduledParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MessageEntity] entity fields to define ObjectBox queries.
class MessageEntity_ {
  /// See [MessageEntity.id].
  static final id = obx.QueryIntegerProperty<MessageEntity>(
    _entities[0].properties[0],
  );

  /// See [MessageEntity.uuid].
  static final uuid = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[1],
  );

  /// See [MessageEntity.role].
  static final role = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[2],
  );

  /// See [MessageEntity.text].
  static final text = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[3],
  );

  /// See [MessageEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<MessageEntity>(
    _entities[0].properties[4],
  );

  /// See [MessageEntity.tasksJson].
  static final tasksJson = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[5],
  );

  /// See [MessageEntity.embedding].
  static final embedding = obx.QueryHnswProperty<MessageEntity>(
    _entities[0].properties[6],
  );

  /// See [MessageEntity.project].
  static final project = obx.QueryRelationToOne<MessageEntity, ProjectEntity>(
    _entities[0].properties[7],
  );
}

/// [ProjectEntity] entity fields to define ObjectBox queries.
class ProjectEntity_ {
  /// See [ProjectEntity.id].
  static final id = obx.QueryIntegerProperty<ProjectEntity>(
    _entities[1].properties[0],
  );

  /// See [ProjectEntity.uuid].
  static final uuid = obx.QueryStringProperty<ProjectEntity>(
    _entities[1].properties[1],
  );

  /// See [ProjectEntity.name].
  static final name = obx.QueryStringProperty<ProjectEntity>(
    _entities[1].properties[2],
  );

  /// See [ProjectEntity.description].
  static final description = obx.QueryStringProperty<ProjectEntity>(
    _entities[1].properties[3],
  );

  /// See [ProjectEntity.createdAt].
  static final createdAt = obx.QueryStringProperty<ProjectEntity>(
    _entities[1].properties[4],
  );

  /// See [ProjectEntity.colorHex].
  static final colorHex = obx.QueryStringProperty<ProjectEntity>(
    _entities[1].properties[5],
  );

  /// see [ProjectEntity.messages]
  static final messages = obx.QueryBacklinkToMany<MessageEntity, ProjectEntity>(
    MessageEntity_.project,
  );
}

/// [CalendarTaskEntity] entity fields to define ObjectBox queries.
class CalendarTaskEntity_ {
  /// See [CalendarTaskEntity.id].
  static final id = obx.QueryIntegerProperty<CalendarTaskEntity>(
    _entities[2].properties[0],
  );

  /// See [CalendarTaskEntity.uuid].
  static final uuid = obx.QueryStringProperty<CalendarTaskEntity>(
    _entities[2].properties[1],
  );

  /// See [CalendarTaskEntity.taskName].
  static final taskName = obx.QueryStringProperty<CalendarTaskEntity>(
    _entities[2].properties[2],
  );

  /// See [CalendarTaskEntity.description].
  static final description = obx.QueryStringProperty<CalendarTaskEntity>(
    _entities[2].properties[3],
  );

  /// See [CalendarTaskEntity.dueDate].
  static final dueDate = obx.QueryDateProperty<CalendarTaskEntity>(
    _entities[2].properties[4],
  );

  /// See [CalendarTaskEntity.calendarDate].
  static final calendarDate = obx.QueryDateProperty<CalendarTaskEntity>(
    _entities[2].properties[5],
  );

  /// See [CalendarTaskEntity.priority].
  static final priority = obx.QueryIntegerProperty<CalendarTaskEntity>(
    _entities[2].properties[6],
  );

  /// See [CalendarTaskEntity.timeToComplete].
  static final timeToComplete = obx.QueryIntegerProperty<CalendarTaskEntity>(
    _entities[2].properties[7],
  );

  /// See [CalendarTaskEntity.links].
  static final links = obx.QueryStringProperty<CalendarTaskEntity>(
    _entities[2].properties[8],
  );

  /// See [CalendarTaskEntity.projectId].
  static final projectId = obx.QueryStringProperty<CalendarTaskEntity>(
    _entities[2].properties[9],
  );

  /// See [CalendarTaskEntity.messageId].
  static final messageId = obx.QueryStringProperty<CalendarTaskEntity>(
    _entities[2].properties[10],
  );

  /// See [CalendarTaskEntity.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<CalendarTaskEntity>(
    _entities[2].properties[11],
  );

  /// See [CalendarTaskEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<CalendarTaskEntity>(
    _entities[2].properties[12],
  );

  /// See [CalendarTaskEntity.originalTaskId].
  static final originalTaskId = obx.QueryStringProperty<CalendarTaskEntity>(
    _entities[2].properties[13],
  );

  /// See [CalendarTaskEntity.startTime].
  static final startTime = obx.QueryStringProperty<CalendarTaskEntity>(
    _entities[2].properties[14],
  );

  /// See [CalendarTaskEntity.endTime].
  static final endTime = obx.QueryStringProperty<CalendarTaskEntity>(
    _entities[2].properties[15],
  );

  /// See [CalendarTaskEntity.isManuallyScheduled].
  static final isManuallyScheduled =
      obx.QueryBooleanProperty<CalendarTaskEntity>(_entities[2].properties[16]);
}
